---
title: "Project organization, data import, file paths"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(janitor)
```

```{r}
stl_lead <-read_csv(here::here("data", "stl_blood_lead.csv"))

```

```{r}

stl_lead <- stl_lead %>% clean_names()

```

Add new column showing proportion of white population:

```{r}

stl_lead_prop <- stl_lead %>% 
  dplyr::mutate(prop_white = (white / total_pop)*100)

```

Now create a scatter plot

```{r}
scatterplot_1 <- ggplot(stl_lead_prop,
       aes(x = prop_white,
           y = pct_elevated)) +
  geom_point(size = 2, alpha = 0.5, color = "deeppink1") +
  ggtitle("Percentage of children with elevated blood lead levels")


```

Elevated levels of lead in blood tests appear less frequently in populatons where there are more white children. More of the children in areas where the percentage of the populaton is less than 75% white have higher elevated blood lead levels.

```{r}
#| fig-height: 5
#| fig-width: 5
scatterplot_1
```

```{r}
ggsave(here::here("figs", "scatterplot_1.png"), height = 5, width = 6)
```


```{r}
histogram_1 <- ggplot(data = stl_lead_prop, 
                      aes(x = pct_elevated),
                      color = "magenta4") +
  geom_histogram(color = "black", fill = "magenta4")
```

```{r}
#| fig-height: 5
#| fig-width: 5
histogram_1
```

```{r}
ggsave(here::here("figs", "histogram_1.png"),
       height = 6,
       width = 5)
```

